### ISSUE TITLE
Push wheel files to PyPI

### ISSUE THREAD

**Issue by ZeroCool2u** [us-bea/beaapi#16]
Please consider pushing new releases to PyPI, so that our internal package security scanners can more easily be automated. 

There's a nice tutorial on how to do it here: https://packaging.python.org/en/latest/tutorials/packaging-projects/#uploading-the-distribution-archives

It can be fairly easily automated too via GitHub actions.

**Comment by deanmalmgren** [comment]
Yes please; this would be very helpful. 

As a workaround, I added the following to my `pyproject.toml` file to install w/ poetry (or ev):

```toml
[tool.poetry.dependencies]
beaapi = {git = "ssh://git@github.com/us-bea/beaapi.git", branch = "main"}
```
